"""added relationships comment

Revision ID: 51a79bc90678
Revises: 87357285401b
Create Date: 2023-02-17 22:18:57.401588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a79bc90678'
down_revision = '87357285401b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
