"""create comment post relations

Revision ID: 62f5d4d45bfa
Revises: 6ce9a5c732d6
Create Date: 2023-02-17 21:53:58.219587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f5d4d45bfa'
down_revision = '6ce9a5c732d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
