"""added relationships

Revision ID: 87357285401b
Revises: 62f5d4d45bfa
Create Date: 2023-02-17 22:08:36.359837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87357285401b'
down_revision = '62f5d4d45bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
