"""Added more relationships

Revision ID: 90bf53bcc3cb
Revises: 51a79bc90678
Create Date: 2023-02-18 17:56:03.129948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bf53bcc3cb'
down_revision = '51a79bc90678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
